server:
  port: 8001

spring:
  application:
    name: light-eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    # 这两个false表示这个服务为eureka server
    fetch-registry: false
    register-with-eureka: false
  service-url:
    # 服务地址
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/